apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "frontend", "namespace": "foobar", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: frontend
    name: frontend-pipeline
    template: application-template-development-pipeline
  name: frontend-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        git branch: 'eap-7', url: 'http://gogs:3000/gogs/insults.git'
        sh "mvn clean install -DskipTests=true"
        stage 'test'
        sh "mvn test"
        openshiftBuild(buildConfig: 'frontend', showBuildLogs: 'true', namespace: 'foobar')
        stage 'build'
        openshiftBuild(buildConfig: 'frontend', showBuildLogs: 'true', namespace: 'foobar')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'frontend', namespace: 'foobar')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
