apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "frontend", "namespace": "foobarstage", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: frontend
    name: testing-pipeline
    template: application-template-testing-pipeline
  name: testing-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'tag'
        openshiftTag(namespace: 'foobar', sourceStream: 'frontend', sourceTag: 'latest', destinationNamespace: 'foobarstage', destinationStream: 'frontend', destinationTag: 'tostage')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'frontend', namespace: 'foobatstage')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
