apiVersion: v1
kind: Template
metadata:
  name: jenkins-pipeline-from-file
parameters:
- name: NAME
  description: Name of the pipeline
  displayName: Application Name
  required: true
  value: 
- name: GIT_SOURCE_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
  value: https://example.com/foo/bar.git
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: ${NAME}
  spec:
    source:
      git:
        uri: ${GIT_SOURCE_URL}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
